Fix logging

diff --git a/env_setup b/env_setup
--- a/env_setup
+++ b/env_setup
@@ -9,7 +9,7 @@ LOGFILE=$WORK_DIR/update.log
 
 #yq is required
 if ! [ -x "$(command -v yq)" ]; then
-    echo -e "\nDownloading Yq"
+    echo -ne "\nDownloading Yq"
     wget https://github.com/mikefarah/yq/releases/download/v4.26.1/yq_linux_amd64.tar.gz -O - 2>/dev/null | tar xz && mv yq_linux_amd64 /usr/bin/yq
     on_error $? "\nERROR: yq needs to be installed before running this script\n"
 fi
@@ -21,11 +21,11 @@ if [[ -f $CONFIG_FILE ]]; then
             read -p $'\nResume setup from last exit? (y/n): ' setup_resume
             case $setup_resume in
             [yY])
-                echo -e "\nResuming Setup .."
+                echo -ne "\nResuming Setup .."
                 break
                 ;;
             [nN])
-                echo -e "\nRestarting Setup .."
+                echo -ne "\nRestarting Setup .."
                 reset_progress
                 source $WORK_DIR/set_progress.sh
                 break
@@ -37,7 +37,7 @@ if [[ -f $CONFIG_FILE ]]; then
 
     #VALIDATE AND CONFIRM CONFIGS
     if [ $CONFIGS != 'OK' ]; then
-        action_comment="1.Validating Configuration File"
+        echo -ne "\nValidating Configuration File ...." | tee -a $LOGFILE
         source $CONFIG_FILE
         #Confirm required config file variables are not empty
         ip_prefix='_IP'
@@ -56,13 +56,9 @@ if [[ -f $CONFIG_FILE ]]; then
             fi
             let num=num+1
         done
-        [ $num -lt 2 ] && {
-            on_error 1 "Ensure at least 1 master ip and their respective mac address are defined" $action_comment
-        }
-        # [ $num -lt 6 ] && { on_error 1 "Ensure at least 3 master ips and their respective mac addresses are defined"; }
-        [ $(expr $num % 2) != 0 ] && {
-            on_error 1 "Ensure all masters specified in the config file include their ip and mac addresses" $action_comment
-        }
+        [ $num -lt 2 ] && { on_error 1 "\nEnsure at least 1 master ip and their respective mac address are defined"; }
+        # [ $num -lt 6 ] && { on_error 1 "\nEnsure at least 3 master ips and their respective mac addresses are defined"; }
+        [ $(expr $num % 2) != 0 ] && { on_error 1 "\nEnsure all masters specified in the config file include their ip and mac addresses"; }
         let num=num/2
         sed -i "s/MASTERS=0/MASTERS=$num/g" $WORK_DIR/set_progress.sh
         source $WORK_DIR/set_progress.sh
@@ -74,9 +70,7 @@ if [[ -f $CONFIG_FILE ]]; then
             let num=num+1
         done
         if [ $num != 0 ]; then
-            [ $(expr $num % 2) != 0 ] && {
-                on_error 1 "Ensure all workers specified in the config file include their ip and mac addresses" $action_comment
-            }
+            [ $(expr $num % 2) != 0 ] && { on_error 1 "\nEnsure all workers specified in the config file include their ip and mac addresses"; }
             let num=num/2
             sed -i "s/WORKERS=0/WORKERS=$num/g" $WORK_DIR/set_progress.sh
             source $WORK_DIR/set_progress.sh
@@ -91,7 +85,7 @@ if [[ -f $CONFIG_FILE ]]; then
             [[ ${i} = *$ip_prefix ]] && valid_ip ${!i} ${i}
             [[ ${i} = *$mac_prefix ]] && valid_mac ${!i} ${i}
         done
-        success_logger $action_comment
+        echo -ne "OK" | tee -a $LOGFILE
         set_progress CONFIGS
         set_progress RESUME
     fi
@@ -143,25 +137,25 @@ EOF
     cd $WORK_DIR/ocp4_ansible/
     if [ $PRE_REQS != 'OK' ]; then
         #Checking pre-requisites
-        action_comment="Checking pre-requisites"
-        echo -e "\nConfirming OS Version .." >>$LOGFILE
+        echo -ne "\nChecking pre-requisites ..." | tee -a $LOGFILE
+        echo -ne "\nConfirming OS Version .." | tee -a $LOGFILE
         source /etc/os-release >>$LOGFILE 2>&1
-        on_error $? "Could not confirm OS version. Check logs at $LOGFILE\n" $action_comment
-        [ -z "$VERSION" ] && {on_error 1 "Could not confirm OS Version"}
-        [[ $VERSION == 8* ]] && echo -e "\nSuccessfully Confirmed OS Version" || on_error 1 "\nPlease run this setup on Red Hat Linux version 8.*.EXITING\n"
+        on_error $? "Could not confirm OS version. Check logs at $LOGFILE\n"
+        [ -z "$VERSION" ] && {on_error 1 "\nCould not confirm OS Version"}
+        [[ $VERSION == 8* ]] && echo -ne "\nSuccessfully Confirmed OS Version" || on_error 1 "\n\nPlease run this setup on Red Hat Linux version 8.*.EXITING\n"
 
         if [ $SETUP_DNS == 1 ]; then
-            echo -e "\nSetting up DNS .." | tee -a $LOGFILE
+            echo -ne "\nSetting up DNS .." | tee -a $LOGFILE
             sudo yum -y install bind bind-utils >>$LOGFILE 2>&1
             sudo systemctl enable named >>$LOGFILE 2>&1
             on_error $? "Issue installing bind and bind-utils package. Check logs at $LOGFILE"
             sudo cp files/set-dns-serial.sh /usr/local/bin/ && sudo chmod a+x /usr/local/bin/set-dns-serial.sh
             ansible-playbook tasks/configure_bind_dns.yml >>$LOGFILE 2>&1
             on_error $? "Issue setting up DNS. Check logs at $LOGFILE"
-            echo -e "\nSuccessfully setup DNS" | tee -a $LOGFILE
-            echo -e "\nOK\n" >>$LOGFILE
+            echo -ne "\nSuccessfully setup DNS" | tee -a $LOGFILE
+            echo -ne "\nOK\n" >>$LOGFILE
         fi
-        echo -e "\nConfirming Forward and Reverse DNS Resolution" | tee -a $LOGFILE
+        echo -ne "\nConfirming Forward and Reverse DNS Resolution" | tee -a $LOGFILE
         #For masters and workers
         for ((i = 1; i <= $MASTERS; i++)); do
             dns_resolve master0$i.ocp4.$BASE_DOMAIN_NAME MASTER_0$i"_IP"
@@ -179,31 +173,31 @@ EOF
             *) dns_resolve $i $HELPER_IP ;;
             esac
         done
-        echo -e "\nSuccessfully Confirmed DNS requirements" | tee -a $LOGFILE
-        echo -e "\nOK\n" >>$LOGFILE
+        echo -ne "\nSuccessfully Confirmed DNS requirements" | tee -a $LOGFILE
+        echo -ne "\nOK\n" >>$LOGFILE
         set_progress PRE_REQS
     fi
 
     #Begin environment setup
     if [ $DHCP != 'OK' ]; then
-        echo -e "\nSTARTING SETUP OF ENVIRONMENT SERVICES ..." | tee -a $LOGFILE
-        echo -e "\nInstalling DHCP .." | tee -a $LOGFILE
+        echo -ne "\nSTARTING SETUP OF ENVIRONMENT SERVICES ..." | tee -a $LOGFILE
+        echo -ne "\nInstalling DHCP .." | tee -a $LOGFILE
         sudo yum -y remove dhcp-server >>$LOGFILE 2>&1
         sudo yum -y install dhcp-server >>$LOGFILE 2>&1
         sudo systemctl enable dhcpd >>$LOGFILE 2>&1
         sudo mv /etc/dhcp/dhcpd.conf /etc/dhcp/dhcpd.conf.bak >>$LOGFILE 2>&1
         on_error $? "Issue installing dhcpd package. Check logs at $LOGFILE"
-        echo -e "\nOK\n" >>$LOGFILE
+        echo -ne "\nOK\n" >>$LOGFILE
 
-        echo -e "\nSetting up DHCP .." | tee -a $LOGFILE
+        echo -ne "\nSetting up DHCP .." | tee -a $LOGFILE
         ansible-playbook tasks/configure_dhcpd.yml >>$LOGFILE 2>&1
         on_error $? "Issue setting up DHCP. Check logs at $LOGFILE"
-        echo -e "\nSuccessfully installed DHCP" | tee -a $LOGFILE
-        echo -e "\nOK\n" >>$LOGFILE
+        echo -ne "\nSuccessfully installed DHCP" | tee -a $LOGFILE
+        echo -ne "\nOK\n" >>$LOGFILE
         set_progress DHCP
     fi
     if [ $TFTP_INSTALL != 'OK' ]; then
-        echo -e "\nInstalling TFTP Server .." | tee -a $LOGFILE
+        echo -ne "\nInstalling TFTP Server .." | tee -a $LOGFILE
         sudo yum remove -y tftp-server syslinux >>$LOGFILE 2>&1
         sudo yum -y install tftp-server syslinux >>$LOGFILE 2>&1
         sudo firewall-cmd --add-service=tftp --permanent >>$LOGFILE 2>&1
@@ -219,8 +213,8 @@ EOF
         sudo systemctl daemon-reload >>$LOGFILE 2>&1
         sudo systemctl enable --now tftp helper-tftp >>$LOGFILE 2>&1
         on_error $? "Issue installing TFTP. Check logs at $LOGFILE"
-        echo -e "\nSuccessfully installed TFTP" | tee -a $LOGFILE
-        echo -e "\nOK\n" >>$LOGFILE
+        echo -ne "\nSuccessfully installed TFTP" | tee -a $LOGFILE
+        echo -ne "\nOK\n" >>$LOGFILE
         set_progress TFTP_INSTALL
     fi
     sudo rm -rf /var/lib/tftpboot >>$LOGFILE 2>&1
@@ -229,7 +223,7 @@ EOF
     sudo mkdir -p /var/lib/tftpboot/rhcos >>$LOGFILE 2>&1
 
     if [ $RHCOS_KERNEL != 'OK' ]; then
-        echo -e "\nDownloading RHCOS Kernel and Installer Image. Please wait this might take some time .." | tee -a $LOGFILE
+        echo -ne "\nDownloading RHCOS Kernel and Installer Image. Please wait this might take some time .." | tee -a $LOGFILE
         wget https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/latest/rhcos-installer-kernel-x86_64 >>$LOGFILE 2>&1
         on_error $? "Could not download kernel file. Check logs at $LOGFILE"
         sudo mv rhcos-installer-kernel-x86_64 /var/lib/tftpboot/rhcos/kernel >>$LOGFILE 2>&1
@@ -242,12 +236,12 @@ EOF
         set_progress RHCOS_INSTALLER
     fi
     sudo restorecon -RFv /var/lib/tftpboot/rhcos >>$LOGFILE 2>&1
-    echo -e "\nSuccessfully Downloaded" >>$LOGFILE
+    echo -ne "\nSuccessfully Downloaded" >>$LOGFILE
     ls /var/lib/tftpboot/rhcos >>$LOGFILE 2>&1
-    echo -e "\nOK\n" >>$LOGFILE
+    echo -ne "\nOK\n" >>$LOGFILE
 
     if [ $APACHE != 'OK' ]; then
-        echo -e "\nInstalling Apache .." | tee -a $LOGFILE
+        echo -ne "\nInstalling Apache .." | tee -a $LOGFILE
         sudo yum -y remove httpd >>$LOGFILE 2>&1
         sudo yum -y install httpd >>$LOGFILE 2>&1
         on_error $? "Could not install Apache. Check logs at $LOGFILE"
@@ -257,34 +251,34 @@ EOF
         sudo firewall-cmd --reload >>$LOGFILE 2>&1
         sudo mkdir -p /var/www/html/rhcos >>$LOGFILE 2>&1
         if [ $RHCOS_ROOTFS != 'OK' ]; then
-            echo -e "\nDownloading Red HatCoreOSroofs image. Please wait this might take some time .." | tee -a $LOGFILE
+            echo -ne "\nDownloading Red HatCoreOSroofs image. Please wait this might take some time .." | tee -a $LOGFILE
             wget https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.10/latest/rhcos-live-rootfs.x86_64.img >>$LOGFILE 2>&1
             on_error $? "Could not download Red Hat CoreOSrootfs image. Check logs at $LOGFILE"
-            echo -e "\nRed Hat CoreOSrootfs image downloaded" | tee -a $LOGFILE
+            echo -ne "\nRed Hat CoreOSrootfs image downloaded" | tee -a $LOGFILE
             sudo mv rhcos-live-rootfs.x86_64.img /var/www/html/rhcos/rootfs.img >>$LOGFILE 2>&1
             sudo restorecon -RFv /var/www/html/rhcos >>$LOGFILE 2>&1
             set_progress RHCOS_ROOTFS
         fi
-        echo -e "\nSuccessfully setup Apache" | tee -a $LOGFILE
-        echo -e "\nOK\n" >>$LOGFILE
+        echo -ne "\nSuccessfully setup Apache" | tee -a $LOGFILE
+        echo -ne "\nOK\n" >>$LOGFILE
         set_progress APACHE
     fi
     if [ $TFTP_SETUP != 'OK' ]; then
-        echo -e "\nConfiguring TFTP Server .." | tee -a $LOGFILE
+        echo -ne "\nConfiguring TFTP Server .." | tee -a $LOGFILE
         ansible-playbook tasks/configure_tftp_pxe.yml >>$LOGFILE 2>&1
         on_error $? "Issue Setting up TFTP Server. Check logs at $LOGFILE"
-        echo -e "\nSuccessfully setup TFTP" | tee -a $LOGFILE
+        echo -ne "\nSuccessfully setup TFTP" | tee -a $LOGFILE
         set_progress TFTP_SETUP
     fi
     if [ $HAPROXY != 'OK' ]; then
-        echo -e "\nInstalling HAProxy .." | tee -a $LOGFILE
+        echo -ne "\nInstalling HAProxy .." | tee -a $LOGFILE
         sudo yum remove -y haproxy >>$LOGFILE 2>&1
         sudo yum install -y haproxy >>$LOGFILE 2>&1
         on_error $? "Issue Installing HAProxy. Check logs at $LOGFILE"
         sudo setsebool -P haproxy_connect_any 1 >>$LOGFILE 2>&1
         sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default >>$LOGFILE 2>&1
 
-        echo -e "\nConfiguring HAProxy .." | tee -a $LOGFILE
+        echo -ne "\nConfiguring HAProxy .." | tee -a $LOGFILE
         ansible-playbook tasks/configure_haproxy_lb.yml >>$LOGFILE 2>&1
         on_error $? "Issue Configuring HAProxy. Check logs at $LOGFILE"
         sudo semanage port -a 6443 -t http_port_t -p tcp >>$LOGFILE 2>&1
@@ -294,15 +288,15 @@ EOF
         sudo firewall-cmd --add-service={http,https} --permanent >>$LOGFILE 2>&1
         sudo firewall-cmd --add-port={6443,22623}/tcp --permanent >>$LOGFILE 2>&1
         sudo firewall-cmd --reload >>$LOGFILE 2>&1
-        echo -e "\nSuccessfully setup HAProxy" | tee -a $LOGFILE
-        echo -e "\nOK\n" >>$LOGFILE
+        echo -ne "\nSuccessfully setup HAProxy" | tee -a $LOGFILE
+        echo -ne "\nOK\n" >>$LOGFILE
         set_progress HAPROXY
     fi
-    echo -e "\nEnvironment Setup Successful" | tee -a $LOGFILE
+    echo -ne "\nEnvironment Setup Successful" | tee -a $LOGFILE
 
     if [ $OPENSHIFT_CLIENTS != 'OK' ]; then
-        echo -e "\nDownloading openshift-install, client binaries and generating SSH Keys .." | tee -a $LOGFILE
-        echo -e "\nDownloading openshift client binaries" >>$LOGFILE
+        echo -ne "\nDownloading openshift-install, client binaries and generating SSH Keys .." | tee -a $LOGFILE
+        echo -ne "\nDownloading openshift client binaries" >>$LOGFILE
         rm -f openshift-client-linux.tar.gz >>$LOGFILE 2>&1
         wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-4.10/openshift-client-linux.tar.gz >>$LOGFILE 2>&1
         on_error $? "Could not download openshift client binaries. Check logs at $LOGFILE"
@@ -311,12 +305,12 @@ EOF
         sudo mv oc kubectl /usr/local/bin >>$LOGFILE 2>&1
         rm -f README.md LICENSE openshift-client-linux.tar.gz >>$LOGFILE 2>&1
         echo -e "Successfully downloaded and installed openshshift client libraries" | tee -a $LOGFILE
-        echo -e "\nOK\n" >>$LOGFILE
+        echo -ne "\nOK\n" >>$LOGFILE
         set_progress OPENSHIFT_CLIENTS
     fi
 
     if [ $OCP_INSTALLER != "OK" ]; then
-        echo -e "\nDownloading openshift install" | tee -a $LOGFILE
+        echo -ne "\nDownloading openshift install" | tee -a $LOGFILE
         rm -f openshift-install-linux.tar.gz >>$LOGFILE 2>&1
         wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-4.10/openshift-install-linux.tar.gz >>$LOGFILE 2>&1
         on_error $? "Could not download openshift-nstall. Check logs at $LOGFILE"
@@ -334,7 +328,7 @@ EOF
         on_error $? "Could not generate SSH Keys. Check logs at $LOGFILE"
         echo -e "SSH keys generated" | tee -a $LOGFILE
 
-        echo -e "\nPreparing to generate ignition files.." | tee -a $LOGFILE
+        echo -ne "\nPreparing to generate ignition files.." | tee -a $LOGFILE
         echo -e "Getting pull secret" | tee -a $LOGFILE
         source files/secret.sh >>$LOGFILE 2>&1
 
@@ -351,9 +345,9 @@ EOF
         echo -e "Creating Ignition Files" | tee -a $LOGFILE
         openshift-install --dir ~/ocp4 create ignition-configs >>$LOGFILE 2>&1
         on_error $? "Unable to create ignition files. Check logs at $LOGFILE"
-        echo -e "\nIgnition Files successfully generated" | tee -a $LOGFILE
+        echo -ne "\nIgnition Files successfully generated" | tee -a $LOGFILE
 
-        echo -e "\nCopying ignition files to Apache .." | tee -a $LOGFILE
+        echo -ne "\nCopying ignition files to Apache .." | tee -a $LOGFILE
         sudo rm -rf /var/www/html/ignition && sudo mkdir -p /var/www/html/ignition >>$LOGFILE 2>&1
         sudo cp -v ~/ocp4/*.ign /var/www/html/ignition >>$LOGFILE 2>&1
         sudo chmod 644 /var/www/html/ignition/*.ign >>$LOGFILE 2>&1
@@ -361,7 +355,7 @@ EOF
         set_progress OCP_FILES
     fi
 
-    echo -e "\nConfirming all services are running .." | tee -a $LOGFILE
+    echo -ne "\nConfirming all services are running .." | tee -a $LOGFILE
     SERVICES=(haproxy dhcpd tftp httpd)
     for i in ${SERVICES[@]}; do
         systemctl enable $i >>$LOGFILE >>$LOGFILE 2>&1
@@ -373,7 +367,7 @@ EOF
         fi
     done
 
-    echo -e "\nENVIRONMENT SERVICES SETUP SUCCESSFUL\n" | tee -a $LOGFILE
+    echo -ne "\nENVIRONMENT SERVICES SETUP SUCCESSFUL\n" | tee -a $LOGFILE
     reset_progress
 else
     echo "Cannot find config file. QUITING" | tee -a $LOGFILE
